### PR TITLE
#if gate a few methods to get things working with USD 23.11

### PR DESCRIPTION
**Pull request by expenses**
Hi, these changes are required in order to get bbl-usd compiling and linking on Arch Linux with the [usd package](https://archlinux.org/packages/extra/x86_64/usd/) (which is monolithic) (version 23.11-5). They \*should\* make things more flexible in general unless I've done something wrong :) I did also test with the pre-built USD [package that Nvidia provides](https://developer.nvidia.com/usd) but ran into linking issues here - I think due to a mismatch between the package and system python versions.

As far as I know, the methods I had to remove were removed in USD between versions 23.08 and 23.11. I'm not entirely sure why I needed to modify the iterator incrementation functions though. Possibly because of changes to babble?

### CODE REVIEW

**Comment by anderslanglands** [comment]
Hi @expenses thanks for these! I've actually got a big update still to push, so you'll need to rebase once that's done and will probably have some more differences to account for in 23.11.

Rather than just deleting the removed methods, could you put them in a `#if (USD_VERSION > 2308)` (not sure what the appropriate preprocessor incantation would actually be here, but you get the idea)?

**Comment by anderslanglands** [comment]
Oh and the iterator difference is probably to do with the ongoing effort to remove boost from USD

**Comment by expenses** [comment]
@anderslanglands Cool yep, I'm happy to just leave this here and use them for my purposes in the meantime.

**Comment by anderslanglands** [comment]
Hmm unfortunately PXR_LIBRARIES breaks linking on Windows because the generated list of libraries is too long to pass to my hacky echo linker script. Not sure what to do here.

**Comment by expenses** [comment]
> Hmm unfortunately PXR_LIBRARIES breaks linking on Windows because the generated list of libraries is too long to pass to my hacky echo linker script. Not sure what to do here.

Ah okay, the second best thing might be to check `PXR_LIBRARIES` for `usd_ms` and use that if so, `usd usdGeom sdf sdr ndr pcp` otherwise.

**Comment by anderslanglands** [comment]
All good I've figured out a (somewhat nasty) solution that parses Ninja's build file...

**Comment by expenses** [comment]
Cool, the `PXR_LIBRARIES` stuff is working now. 

> Rather than just deleting the removed methods, could you put them in a `#if (USD_VERSION > 2308)` (not sure what the appropriate preprocessor incantation would actually be here, but you get the idea)?

I'll get working on this in a bit.

**Comment by expenses** [comment]
> > Rather than just deleting the removed methods, could you put them in a `#if (USD_VERSION > 2308)` (not sure what the appropriate preprocessor incantation would actually be here, but you get the idea)?
> 
> I'll get working on this in a bit.

Okay, done. These changes will probably need to be tested on 23.08 but at least they compile with 23.11.

**Comment by anderslanglands** [comment]
Thanks! I'll YOLO this and fix up any breakage on main

**Pull request merged**
